# DSCI 521: Methods for analysis and interpretation <br> Chapter 1: Processing numeric data

## Exercises
Note: numberings refer to the main notes.

#### 1.0.2.3 Exercise: Creating a matrix 
Using the above matrix-generation techniques, create a 2x2 identity matrix.

In [2]:
import numpy as np

identit2 = np.zeros((2,2))

for i in range(len(identit2)):
    identit2[i,i] = 1

print(identit2)
print(np.identity(2))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


#### 1.0.2.5 Exercise: broadcast operations 
Square each element in the matrix `A` without using any loops.

In [3]:
A = [1, 2, 3, 4, 5]

A = np.array(A)

A_squares = A ** 2

print(A_squares)

A_squares = np.power(A, 2)

print(A_squares)

[ 1  4  9 16 25]
[ 1  4  9 16 25]


#### 1.1.2.2 Exercise: vector arithmetic 
Calculate `A` - `B` for the provided vectors, without using a loop.

In [4]:
A = [i for i in range(5)]
B = [-i for i in range(5)]

print(A)
print(B)

A = np.array(A)
B = np.array(B)

print(A - B)

[0, 1, 2, 3, 4]
[0, -1, -2, -3, -4]
[0 2 4 6 8]


In [5]:
## compute euclidean norm of A - B:
print(np.power(sum(np.power(A - B, 2)), 0.5), np.power(sum(np.power(A, 2)), 0.5))

10.954451150103322 5.477225575051661


#### 1.1.2.5 Exercise: scalar multiplication
Divide each element in the above vector `v` by 4.

In [9]:
v = np.array([9., 2., 4., 8., 1.])

v / 4

array([2.25, 0.5 , 1.  , 2.  , 0.25])

#### 1.1.2.7 Exercise: pointwise vector multiplication 
Perform pointwise multiplication between `v` divided by 4 which you calculated above, and `u`.

In [10]:
u = np.array([-5., 3.7, 2., 10., 0.])

(v / 4) * u

array([-11.25,   1.85,   2.  ,  20.  ,   0.  ])

#### 1.1.2.9 Exercise: inner products 
Find the dot product of the provided array `z` with `u` and `v`, respectively, from above.

In [8]:
z = np.array([1, 2, 3, 4, 5])

u = np.array([-5., 3.7, 2., 10., 0.])
v = np.array([9., 2., 4., 8., 1.])

print(z.dot(u))
print(z.dot(v))

48.4
62.0


#### 1.1.2.11 Exercise: cosine similarity 
Find the cosine similarity of the vectors `a` and `b`.

In [11]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

0.0

#### 1.1.3.3 Exercise: Matrix indexing 
Print the value in the above matrix `A` located in the bottom-right entry.

In [12]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

print(A[-1,-1])

12


#### 1.1.4.2 Exercise: matrix addition 
Using `A` and `B` from above, find the sum `A` + `B` + `A`.

In [15]:
## define a 4-row by 3-column matrix
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

print(A, '\n')

## define another 4-row by 3-column matrix
B = np.array([
    [ 11,  12,  13],
    [ 14,  15,  16],
    [ 17,  18,  19],
    [ 20,  21,  22]
])

print(B, '\n')

## take the matrix sum of the two
print(2*A + B, "\n\n", A + A + B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]] 

[[13 16 19]
 [22 25 28]
 [31 34 37]
 [40 43 46]] 

 [[13 16 19]
 [22 25 28]
 [31 34 37]
 [40 43 46]]


#### 1.1.4.4 Exercise: Scalar matrix multiplication
Divide each element in the above matrix `A` by 4.

In [21]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

print(A.shape)
print(A/4)

(4, 3)
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]
 [2.5  2.75 3.  ]]
